name: Deploy to EC2

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Copiar código al servidor EC2
      - name: Copy code to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./backend-api/"   # Ruta local del código en GitHub
          target: "/home/ubuntu/facedetection"  # Ruta de destino en el servidor EC2
          strip_components: 1  # Elimina la carpeta raíz "backend-api" al copiar
